export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const TIME_LOGS_ID = process.env.NEXT_PUBLIC_APPWRITE_TIME_LOGS_ID!;
export const CUSTOM_COLUMNS_ID = process.env.NEXT_PUBLIC_APPWRITE_CUSTOM_COLUMNS_ID!;
export const DEFAULT_COLUMN_SETTINGS_ID = process.env.NEXT_PUBLIC_APPWRITE_DEFAULT_COLUMN_SETTINGS_ID!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!
export const ATTACHMENTS_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_ATTACHMENTS_BUCKET_ID!
export const ATTACHMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_ATTACHMENTS_ID!
