export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const TIME_LOGS_ID = process.env.NEXT_PUBLIC_APPWRITE_TIME_LOGS_ID!;
export const SPRINTS_ID = process.env.NEXT_PUBLIC_APPWRITE_SPRINTS_ID!;
export const WORK_ITEMS_ID = process.env.NEXT_PUBLIC_APPWRITE_WORK_ITEMS_ID!;
export const PERSONAL_BACKLOG_ID = process.env.NEXT_PUBLIC_APPWRITE_PERSONAL_BACKLOG_ID!;
export const CUSTOM_COLUMNS_ID = process.env.NEXT_PUBLIC_APPWRITE_CUSTOM_COLUMNS_ID!;
export const DEFAULT_COLUMN_SETTINGS_ID = process.env.NEXT_PUBLIC_APPWRITE_DEFAULT_COLUMN_SETTINGS_ID!;
export const NOTIFICATIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_NOTIFICATIONS_ID!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!
export const ATTACHMENTS_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_ATTACHMENTS_BUCKET_ID!
export const ATTACHMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_ATTACHMENTS_ID!

// Email/Messaging Configuration
export const SMTP_PROVIDER_ID = process.env.NEXT_PUBLIC_APPWRITE_SMTP_PROVIDER_ID!;
export const EMAIL_TOPIC_ID = process.env.NEXT_PUBLIC_APPWRITE_EMAIL_TOPIC_ID!;
